//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBVisits.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mdkEntities : DbContext
    {
        public mdkEntities()
            : base("name=mdkEntities")
        {
        }

        private static mdkEntities _context;

        public static mdkEntities GetContext()
        {
            if (_context == null)
            {
                _context = new mdkEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Корабли> Корабли { get; set; }
        public virtual DbSet<Порты> Порты { get; set; }
        public virtual DbSet<Посещения> Посещения { get; set; }
    }
}
