//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBVisits.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Посещения
    {
        public int Код_посещения { get; set; }
        public int Код_корабля { get; set; }
        public int Код_порта { get; set; }
        public string Дата_прибытия { get; set; }
        public string Дата_отплытия { get; set; }
        public int Номер_причала { get; set; }
        public string Цель_посещения { get; set; }
    
        public virtual Корабли Корабли { get; set; }
        public virtual Порты Порты { get; set; }
    }
}
